/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`config_tls_inbound_domains_create_tls_inbound_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigTlsInboundDomainsCreateTlsInboundDomainsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_tls_inbound_domains_delete_tls_inbound_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigTlsInboundDomainsDeleteTlsInboundDomainsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_tls_inbound_domains_get_tls_inbound_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigTlsInboundDomainsGetTlsInboundDomainsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}


/// Add new tls_inbound_domains entry.
pub async fn config_tls_inbound_domains_create_tls_inbound_domains(configuration: &configuration::Configuration, config_tls_inbound_domains_create_tls_inbound_domains_request: models::ConfigTlsInboundDomainsCreateTlsInboundDomainsRequest) -> Result<models::ConfigTlsInboundDomainsCreateTlsInboundDomainsResponse, Error<ConfigTlsInboundDomainsCreateTlsInboundDomainsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_config_tls_inbound_domains_create_tls_inbound_domains_request = config_tls_inbound_domains_create_tls_inbound_domains_request;

    let uri_str = format!("{}/config/tls-inbound-domains", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    req_builder = req_builder.json(&p_body_config_tls_inbound_domains_create_tls_inbound_domains_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigTlsInboundDomainsCreateTlsInboundDomainsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigTlsInboundDomainsCreateTlsInboundDomainsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigTlsInboundDomainsCreateTlsInboundDomainsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a tls_inbound_domains entry
pub async fn config_tls_inbound_domains_delete_tls_inbound_domains(configuration: &configuration::Configuration, domain: &str) -> Result<models::ConfigTlsInboundDomainsDeleteTlsInboundDomainsResponse, Error<ConfigTlsInboundDomainsDeleteTlsInboundDomainsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_domain = domain;

    let uri_str = format!("{}/config/tls-inbound-domains/{domain}", configuration.base_path, domain=crate::apis::urlencode(p_path_domain));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigTlsInboundDomainsDeleteTlsInboundDomainsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigTlsInboundDomainsDeleteTlsInboundDomainsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigTlsInboundDomainsDeleteTlsInboundDomainsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List tls_inbound_domains entries.
pub async fn config_tls_inbound_domains_get_tls_inbound_domains(configuration: &configuration::Configuration, ) -> Result<models::ConfigTlsInboundDomainsGetTlsInboundDomainsResponse, Error<ConfigTlsInboundDomainsGetTlsInboundDomainsError>> {

    let uri_str = format!("{}/config/tls-inbound-domains", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigTlsInboundDomainsGetTlsInboundDomainsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigTlsInboundDomainsGetTlsInboundDomainsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigTlsInboundDomainsGetTlsInboundDomainsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

