/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`config_tlspolicy_create_tlspolicy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigTlspolicyCreateTlspolicyError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_tlspolicy_delete_tlspolicy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigTlspolicyDeleteTlspolicyError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_tlspolicy_get_tlspolicy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigTlspolicyGetTlspolicyError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_tlspolicy_read_get_tlspolicy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigTlspolicyReadGetTlspolicyError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_tlspolicy_write`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigTlspolicyWriteError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}


/// Add tls_policy entry.
pub async fn config_tlspolicy_create_tlspolicy(configuration: &configuration::Configuration, config_tlspolicy_create_tlspolicy_request: models::ConfigTlspolicyCreateTlspolicyRequest) -> Result<models::ConfigTlspolicyCreateTlspolicyResponse, Error<ConfigTlspolicyCreateTlspolicyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_config_tlspolicy_create_tlspolicy_request = config_tlspolicy_create_tlspolicy_request;

    let uri_str = format!("{}/config/tlspolicy", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    req_builder = req_builder.json(&p_body_config_tlspolicy_create_tlspolicy_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigTlspolicyCreateTlspolicyResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigTlspolicyCreateTlspolicyResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigTlspolicyCreateTlspolicyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a tls_policy entry
pub async fn config_tlspolicy_delete_tlspolicy(configuration: &configuration::Configuration, destination: &str) -> Result<models::ConfigTlspolicyDeleteTlspolicyResponse, Error<ConfigTlspolicyDeleteTlspolicyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_destination = destination;

    let uri_str = format!("{}/config/tlspolicy/{destination}", configuration.base_path, destination=crate::apis::urlencode(p_path_destination));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigTlspolicyDeleteTlspolicyResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigTlspolicyDeleteTlspolicyResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigTlspolicyDeleteTlspolicyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List tls_policy entries.
pub async fn config_tlspolicy_get_tlspolicy(configuration: &configuration::Configuration, ) -> Result<models::ConfigTlspolicyGetTlspolicyResponse, Error<ConfigTlspolicyGetTlspolicyError>> {

    let uri_str = format!("{}/config/tlspolicy", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigTlspolicyGetTlspolicyResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigTlspolicyGetTlspolicyResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigTlspolicyGetTlspolicyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Read tls_policy entry.
pub async fn config_tlspolicy_read_get_tlspolicy(configuration: &configuration::Configuration, destination: &str) -> Result<models::ConfigTlspolicyReadGetTlspolicyResponse, Error<ConfigTlspolicyReadGetTlspolicyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_destination = destination;

    let uri_str = format!("{}/config/tlspolicy/{destination}", configuration.base_path, destination=crate::apis::urlencode(p_path_destination));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigTlspolicyReadGetTlspolicyResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigTlspolicyReadGetTlspolicyResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigTlspolicyReadGetTlspolicyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update tls_policy entry.
pub async fn config_tlspolicy_write(configuration: &configuration::Configuration, destination: &str, config_tlspolicy_write_request: models::ConfigTlspolicyWriteRequest) -> Result<models::ConfigTlspolicyWriteResponse, Error<ConfigTlspolicyWriteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_destination = destination;
    let p_body_config_tlspolicy_write_request = config_tlspolicy_write_request;

    let uri_str = format!("{}/config/tlspolicy/{destination}", configuration.base_path, destination=crate::apis::urlencode(p_path_destination));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    req_builder = req_builder.json(&p_body_config_tlspolicy_write_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigTlspolicyWriteResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigTlspolicyWriteResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigTlspolicyWriteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

