/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`config_domains_create_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigDomainsCreateDomainsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_domains_delete_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigDomainsDeleteDomainsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_domains_get_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigDomainsGetDomainsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_domains_read_get_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigDomainsReadGetDomainsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_domains_write`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigDomainsWriteError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}


/// Add relay domain.
pub async fn config_domains_create_domains(configuration: &configuration::Configuration, config_dkim_create_domains_request: models::ConfigDkimCreateDomainsRequest) -> Result<models::ConfigDomainsCreateDomainsResponse, Error<ConfigDomainsCreateDomainsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_config_dkim_create_domains_request = config_dkim_create_domains_request;

    let uri_str = format!("{}/config/domains", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    req_builder = req_builder.json(&p_body_config_dkim_create_domains_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigDomainsCreateDomainsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigDomainsCreateDomainsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigDomainsCreateDomainsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a relay domain
pub async fn config_domains_delete_domains(configuration: &configuration::Configuration, domain: &str) -> Result<models::ConfigDomainsDeleteDomainsResponse, Error<ConfigDomainsDeleteDomainsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_domain = domain;

    let uri_str = format!("{}/config/domains/{domain}", configuration.base_path, domain=crate::apis::urlencode(p_path_domain));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigDomainsDeleteDomainsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigDomainsDeleteDomainsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigDomainsDeleteDomainsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List relay domains.
pub async fn config_domains_get_domains(configuration: &configuration::Configuration, ) -> Result<models::ConfigDomainsGetDomainsResponse, Error<ConfigDomainsGetDomainsError>> {

    let uri_str = format!("{}/config/domains", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigDomainsGetDomainsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigDomainsGetDomainsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigDomainsGetDomainsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Read Domain data (comment).
pub async fn config_domains_read_get_domains(configuration: &configuration::Configuration, domain: &str) -> Result<models::ConfigDomainsReadGetDomainsResponse, Error<ConfigDomainsReadGetDomainsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_domain = domain;

    let uri_str = format!("{}/config/domains/{domain}", configuration.base_path, domain=crate::apis::urlencode(p_path_domain));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigDomainsReadGetDomainsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigDomainsReadGetDomainsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigDomainsReadGetDomainsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update relay domain data (comment).
pub async fn config_domains_write(configuration: &configuration::Configuration, domain: &str, config_dkim_write_request: models::ConfigDkimWriteRequest) -> Result<models::ConfigDomainsWriteResponse, Error<ConfigDomainsWriteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_domain = domain;
    let p_body_config_dkim_write_request = config_dkim_write_request;

    let uri_str = format!("{}/config/domains/{domain}", configuration.base_path, domain=crate::apis::urlencode(p_path_domain));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    req_builder = req_builder.json(&p_body_config_dkim_write_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigDomainsWriteResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigDomainsWriteResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigDomainsWriteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

