/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`config_fetchmail_create_fetchmail`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigFetchmailCreateFetchmailError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_fetchmail_delete_fetchmail`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigFetchmailDeleteFetchmailError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_fetchmail_get_fetchmail`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigFetchmailGetFetchmailError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_fetchmail_read_get_fetchmail`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigFetchmailReadGetFetchmailError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`config_fetchmail_write`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConfigFetchmailWriteError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}


/// Create fetchmail user configuration.
pub async fn config_fetchmail_create_fetchmail(configuration: &configuration::Configuration, config_fetchmail_create_fetchmail_request: models::ConfigFetchmailCreateFetchmailRequest) -> Result<models::ConfigFetchmailCreateFetchmailResponse, Error<ConfigFetchmailCreateFetchmailError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_config_fetchmail_create_fetchmail_request = config_fetchmail_create_fetchmail_request;

    let uri_str = format!("{}/config/fetchmail", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    req_builder = req_builder.json(&p_body_config_fetchmail_create_fetchmail_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigFetchmailCreateFetchmailResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigFetchmailCreateFetchmailResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigFetchmailCreateFetchmailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a fetchmail configuration entry.
pub async fn config_fetchmail_delete_fetchmail(configuration: &configuration::Configuration, id: &str) -> Result<models::ConfigFetchmailDeleteFetchmailResponse, Error<ConfigFetchmailDeleteFetchmailError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/config/fetchmail/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigFetchmailDeleteFetchmailResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigFetchmailDeleteFetchmailResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigFetchmailDeleteFetchmailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// List fetchmail users.
pub async fn config_fetchmail_get_fetchmail(configuration: &configuration::Configuration, ) -> Result<models::ConfigFetchmailGetFetchmailResponse, Error<ConfigFetchmailGetFetchmailError>> {

    let uri_str = format!("{}/config/fetchmail", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigFetchmailGetFetchmailResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigFetchmailGetFetchmailResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigFetchmailGetFetchmailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Read fetchmail user configuration.
pub async fn config_fetchmail_read_get_fetchmail(configuration: &configuration::Configuration, id: &str) -> Result<models::ConfigFetchmailReadGetFetchmailResponse, Error<ConfigFetchmailReadGetFetchmailError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/config/fetchmail/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigFetchmailReadGetFetchmailResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigFetchmailReadGetFetchmailResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigFetchmailReadGetFetchmailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update fetchmail user configuration.
pub async fn config_fetchmail_write(configuration: &configuration::Configuration, id: &str, config_fetchmail_write_request: Option<models::ConfigFetchmailWriteRequest>) -> Result<models::ConfigFetchmailWriteResponse, Error<ConfigFetchmailWriteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_config_fetchmail_write_request = config_fetchmail_write_request;

    let uri_str = format!("{}/config/fetchmail/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    req_builder = req_builder.json(&p_body_config_fetchmail_write_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConfigFetchmailWriteResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConfigFetchmailWriteResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConfigFetchmailWriteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

