/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`quarantine_blocklist_blocklist`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuarantineBlocklistBlocklistError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`quarantine_blocklist_blocklist_add`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuarantineBlocklistBlocklistAddError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`quarantine_blocklist_blocklist_delete_base`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QuarantineBlocklistBlocklistDeleteBaseError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}


/// Show user blocklist.
pub async fn quarantine_blocklist_blocklist(configuration: &configuration::Configuration, pmail: Option<&str>) -> Result<models::QuarantineBlocklistBlocklistResponse, Error<QuarantineBlocklistBlocklistError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_pmail = pmail;

    let uri_str = format!("{}/quarantine/blocklist", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_pmail {
        req_builder = req_builder.query(&[("pmail", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::QuarantineBlocklistBlocklistResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::QuarantineBlocklistBlocklistResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<QuarantineBlocklistBlocklistError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Add user blocklist entries.
pub async fn quarantine_blocklist_blocklist_add(configuration: &configuration::Configuration, quarantine_blacklist_blacklist_add_request: models::QuarantineBlacklistBlacklistAddRequest) -> Result<models::QuarantineBlocklistBlocklistAddResponse, Error<QuarantineBlocklistBlocklistAddError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_quarantine_blacklist_blacklist_add_request = quarantine_blacklist_blacklist_add_request;

    let uri_str = format!("{}/quarantine/blocklist", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };
    req_builder = req_builder.json(&p_body_quarantine_blacklist_blacklist_add_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::QuarantineBlocklistBlocklistAddResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::QuarantineBlocklistBlocklistAddResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<QuarantineBlocklistBlocklistAddError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete user blocklist entries.
pub async fn quarantine_blocklist_blocklist_delete_base(configuration: &configuration::Configuration, address: &str, pmail: Option<&str>) -> Result<models::QuarantineBlocklistBlocklistDeleteBaseResponse, Error<QuarantineBlocklistBlocklistDeleteBaseError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_address = address;
    let p_query_pmail = pmail;

    let uri_str = format!("{}/quarantine/blocklist", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    req_builder = req_builder.query(&[("address", &p_query_address.to_string())]);
    if let Some(ref param_value) = p_query_pmail {
        req_builder = req_builder.query(&[("pmail", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::QuarantineBlocklistBlocklistDeleteBaseResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::QuarantineBlocklistBlocklistDeleteBaseResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<QuarantineBlocklistBlocklistDeleteBaseError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

