/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`statistics_contact`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsContactError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_detailstats`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsDetailstatsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_domains`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsDomainsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_get_statistics`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsGetStatisticsError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_mail`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsMailError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_mailcount`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsMailcountError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_maildistribution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsMaildistributionError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_receiver`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsReceiverError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_recent`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsRecentError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_recentreceivers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsRecentreceiversError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_rejectcount`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsRejectcountError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_sender`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsSenderError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_spamscores`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsSpamscoresError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`statistics_virus`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatisticsVirusError {
    Status400(models::PmgError),
    Status401(models::PmgError),
    Status403(models::PmgError),
    Status404(models::PmgError),
    Status500(models::PmgError),
    Status501(models::PmgError),
    Status503(models::PmgError),
    UnknownValue(serde_json::Value),
}


/// Contact Address Statistics.
pub async fn statistics_contact(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, filter: Option<&str>, month: Option<i32>, orderby: Option<&str>, starttime: Option<i64>, year: Option<i32>) -> Result<models::StatisticsContactResponse, Error<StatisticsContactError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_filter = filter;
    let p_query_month = month;
    let p_query_orderby = orderby;
    let p_query_starttime = starttime;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/contact", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter {
        req_builder = req_builder.query(&[("filter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_orderby {
        req_builder = req_builder.query(&[("orderby", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsContactResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsContactResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsContactError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Detailed Statistics.
pub async fn statistics_detailstats(configuration: &configuration::Configuration, address: &str, r#type: models::PmgStatisticsTypeEnum, day: Option<i32>, endtime: Option<i64>, filter: Option<&str>, month: Option<i32>, orderby: Option<&str>, starttime: Option<i64>, year: Option<i32>) -> Result<models::StatisticsDetailstatsResponse, Error<StatisticsDetailstatsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_address = address;
    let p_query_type = r#type;
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_filter = filter;
    let p_query_month = month;
    let p_query_orderby = orderby;
    let p_query_starttime = starttime;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/detail", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("address", &p_query_address.to_string())]);
    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter {
        req_builder = req_builder.query(&[("filter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_orderby {
        req_builder = req_builder.query(&[("orderby", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    req_builder = req_builder.query(&[("type", &p_query_type.to_string())]);
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsDetailstatsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsDetailstatsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsDetailstatsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Mail Domains Statistics.
pub async fn statistics_domains(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, month: Option<i32>, starttime: Option<i64>, year: Option<i32>) -> Result<models::StatisticsDomainsResponse, Error<StatisticsDomainsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_month = month;
    let p_query_starttime = starttime;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/domains", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsDomainsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsDomainsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsDomainsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Directory index.
pub async fn statistics_get_statistics(configuration: &configuration::Configuration, ) -> Result<models::StatisticsGetStatisticsResponse, Error<StatisticsGetStatisticsError>> {

    let uri_str = format!("{}/statistics", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsGetStatisticsResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsGetStatisticsResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsGetStatisticsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// General Mail Statistics.
pub async fn statistics_mail(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, month: Option<i32>, starttime: Option<i64>, year: Option<i32>) -> Result<models::StatisticsMailResponse, Error<StatisticsMailError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_month = month;
    let p_query_starttime = starttime;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/mail", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsMailResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsMailResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsMailError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Mail Count Statistics.
pub async fn statistics_mailcount(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, month: Option<i32>, starttime: Option<i64>, timespan: Option<i32>, year: Option<i32>) -> Result<models::StatisticsMailcountResponse, Error<StatisticsMailcountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_month = month;
    let p_query_starttime = starttime;
    let p_query_timespan = timespan;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/mailcount", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_timespan {
        req_builder = req_builder.query(&[("timespan", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsMailcountResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsMailcountResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsMailcountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the count of spam mails grouped by spam score. Count for score 10 includes mails with spam score > 10.
pub async fn statistics_maildistribution(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, month: Option<i32>, starttime: Option<i64>, year: Option<i32>) -> Result<models::StatisticsMaildistributionResponse, Error<StatisticsMaildistributionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_month = month;
    let p_query_starttime = starttime;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/maildistribution", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsMaildistributionResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsMaildistributionResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsMaildistributionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Receiver Address Statistics.
pub async fn statistics_receiver(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, filter: Option<&str>, month: Option<i32>, orderby: Option<&str>, starttime: Option<i64>, year: Option<i32>) -> Result<models::StatisticsReceiverResponse, Error<StatisticsReceiverError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_filter = filter;
    let p_query_month = month;
    let p_query_orderby = orderby;
    let p_query_starttime = starttime;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/receiver", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter {
        req_builder = req_builder.query(&[("filter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_orderby {
        req_builder = req_builder.query(&[("orderby", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsReceiverResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsReceiverResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsReceiverError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Mail Count Statistics.
pub async fn statistics_recent(configuration: &configuration::Configuration, hours: Option<i32>, timespan: Option<i32>) -> Result<models::StatisticsRecentResponse, Error<StatisticsRecentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_hours = hours;
    let p_query_timespan = timespan;

    let uri_str = format!("{}/statistics/recent", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_hours {
        req_builder = req_builder.query(&[("hours", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_timespan {
        req_builder = req_builder.query(&[("timespan", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsRecentResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsRecentResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsRecentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Top recent Mail Receivers (including spam)
pub async fn statistics_recentreceivers(configuration: &configuration::Configuration, hours: Option<i32>, limit: Option<i32>) -> Result<models::StatisticsRecentreceiversResponse, Error<StatisticsRecentreceiversError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_hours = hours;
    let p_query_limit = limit;

    let uri_str = format!("{}/statistics/recentreceivers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_hours {
        req_builder = req_builder.query(&[("hours", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsRecentreceiversResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsRecentreceiversResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsRecentreceiversError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Early SMTP reject count statistic (RBL, PREGREET rejects with postscreen)
pub async fn statistics_rejectcount(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, month: Option<i32>, starttime: Option<i64>, timespan: Option<i32>, year: Option<i32>) -> Result<models::StatisticsRejectcountResponse, Error<StatisticsRejectcountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_month = month;
    let p_query_starttime = starttime;
    let p_query_timespan = timespan;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/rejectcount", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_timespan {
        req_builder = req_builder.query(&[("timespan", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsRejectcountResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsRejectcountResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsRejectcountError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Sender Address Statistics.
pub async fn statistics_sender(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, filter: Option<&str>, month: Option<i32>, orderby: Option<&str>, starttime: Option<i64>, year: Option<i32>) -> Result<models::StatisticsSenderResponse, Error<StatisticsSenderError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_filter = filter;
    let p_query_month = month;
    let p_query_orderby = orderby;
    let p_query_starttime = starttime;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/sender", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter {
        req_builder = req_builder.query(&[("filter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_orderby {
        req_builder = req_builder.query(&[("orderby", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsSenderResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsSenderResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsSenderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get the count of spam mails grouped by spam score. Count for score 10 includes mails with spam score > 10.
pub async fn statistics_spamscores(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, month: Option<i32>, starttime: Option<i64>, year: Option<i32>) -> Result<models::StatisticsSpamscoresResponse, Error<StatisticsSpamscoresError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_month = month;
    let p_query_starttime = starttime;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/spamscores", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsSpamscoresResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsSpamscoresResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsSpamscoresError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get Statistics about detected Viruses.
pub async fn statistics_virus(configuration: &configuration::Configuration, day: Option<i32>, endtime: Option<i64>, month: Option<i32>, starttime: Option<i64>, year: Option<i32>) -> Result<models::StatisticsVirusResponse, Error<StatisticsVirusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_day = day;
    let p_query_endtime = endtime;
    let p_query_month = month;
    let p_query_starttime = starttime;
    let p_query_year = year;

    let uri_str = format!("{}/statistics/virus", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_day {
        req_builder = req_builder.query(&[("day", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_endtime {
        req_builder = req_builder.query(&[("endtime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_month {
        req_builder = req_builder.query(&[("month", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_starttime {
        req_builder = req_builder.query(&[("starttime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_year {
        req_builder = req_builder.query(&[("year", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("CSRFPreventionToken", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StatisticsVirusResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StatisticsVirusResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StatisticsVirusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

