/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessOidcAuthUrlRequest {

    /// Authentication domain ID
    #[serde(rename = "realm")]
    pub realm: String,

    /// Redirection Url. The client should set this to the used server url (location.origin).
    #[serde(rename = "redirect-url")]
    pub redirect_url: String,


}

impl AccessOidcAuthUrlRequest {
    pub fn new(realm: String, redirect_url: String) -> AccessOidcAuthUrlRequest {
        AccessOidcAuthUrlRequest {
            
            realm,
            
            redirect_url,
            
        }
    }
}


