/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessUsersWriteRequest {

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Encrypted password (see `man crypt`)
    #[serde(rename = "crypt_pass", skip_serializing_if = "Option::is_none")]
    pub crypt_pass: Option<String>,

    /// A list of settings you want to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<String>,

    /// Users E-Mail address.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,

    /// Flag to enable or disable the account.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<models::PmgBoolean>,

    /// Account expiration date (seconds since epoch). '0' means no expiration date.
    #[serde(rename = "expire", skip_serializing_if = "Option::is_none")]
    pub expire: Option<i64>,

    /// First name.
    #[serde(rename = "firstname", skip_serializing_if = "Option::is_none")]
    pub firstname: Option<String>,

    /// Keys for two factor auth (yubico).
    #[serde(rename = "keys", skip_serializing_if = "Option::is_none")]
    pub keys: Option<String>,

    /// Last name.
    #[serde(rename = "lastname", skip_serializing_if = "Option::is_none")]
    pub lastname: Option<String>,

    /// Password
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,

    /// Authentication realm.
    #[serde(rename = "realm", skip_serializing_if = "Option::is_none")]
    pub realm: Option<String>,

    /// User role. Role 'root' is reserved for the Unix Superuser.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<models::PmgRoleEnum>,


}

impl AccessUsersWriteRequest {
    pub fn new() -> AccessUsersWriteRequest {
        AccessUsersWriteRequest {
            
            comment: None,
            
            crypt_pass: None,
            
            delete: None,
            
            email: None,
            
            enable: None,
            
            expire: None,
            
            firstname: None,
            
            keys: None,
            
            lastname: None,
            
            password: None,
            
            realm: None,
            
            role: None,
            
        }
    }
}


