/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTfaUpdateWebauthnConfigRequest {

    /// Whether to allow the origin to be a subdomain, rather than the exact URL.
    #[serde(rename = "allow-subdomains", skip_serializing_if = "Option::is_none")]
    pub allow_subdomains: Option<models::PmgBoolean>,

    /// A list of settings you want to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<models::PmgConfigTfaDeleteEnum>,

    /// Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Relying part ID. Must be the domain name without protocol, port or location. Changing this *will* break existing credentials.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// Site origin. Must be a `https://` URL (or `http://localhost`). Should contain the address users type in their browsers to access the web interface. Changing this *may* break existing credentials.
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,

    /// Relying party name. Any text identifier. Changing this *may* break existing credentials.
    #[serde(rename = "rp", skip_serializing_if = "Option::is_none")]
    pub rp: Option<String>,


}

impl ConfigTfaUpdateWebauthnConfigRequest {
    pub fn new() -> ConfigTfaUpdateWebauthnConfigRequest {
        ConfigTfaUpdateWebauthnConfigRequest {
            
            allow_subdomains: None,
            
            delete: None,
            
            digest: None,
            
            id: None,
            
            origin: None,
            
            rp: None,
            
        }
    }
}


