/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigPbsCreatePbsRequest {

    /// Proxmox Backup Server datastore name.
    #[serde(rename = "datastore")]
    pub datastore: String,

    /// Flag to disable (deactivate) the entry.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<models::PmgBoolean>,

    /// Certificate SHA 256 fingerprint.
    #[serde(rename = "fingerprint", skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,

    /// Include statistics in scheduled backups
    #[serde(rename = "include-statistics", skip_serializing_if = "Option::is_none")]
    pub include_statistics: Option<models::PmgBoolean>,

    /// Keep backups for the last <N> different days. If there is more than one backup for a single day, only the latest one is kept.
    #[serde(rename = "keep-daily", skip_serializing_if = "Option::is_none")]
    pub keep_daily: Option<i64>,

    /// Keep backups for the last <N> different hours. If there is more than one backup for a single hour, only the latest one is kept.
    #[serde(rename = "keep-hourly", skip_serializing_if = "Option::is_none")]
    pub keep_hourly: Option<i64>,

    /// Keep the last <N> backups.
    #[serde(rename = "keep-last", skip_serializing_if = "Option::is_none")]
    pub keep_last: Option<i64>,

    /// Keep backups for the last <N> different months. If there is more than one backup for a single month, only the latest one is kept.
    #[serde(rename = "keep-monthly", skip_serializing_if = "Option::is_none")]
    pub keep_monthly: Option<i64>,

    /// Keep backups for the last <N> different weeks. If there ismore than one backup for a single week, only the latest one is kept.
    #[serde(rename = "keep-weekly", skip_serializing_if = "Option::is_none")]
    pub keep_weekly: Option<i64>,

    /// Keep backups for the last <N> different years. If there is more than one backup for a single year, only the latest one is kept.
    #[serde(rename = "keep-yearly", skip_serializing_if = "Option::is_none")]
    pub keep_yearly: Option<i64>,

    /// Proxmox Backup Server namespace in the datastore, defaults to the root NS.
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,

    /// Specify when to notify via e-mail
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<models::PmgNotifyEnum>,

    /// Password or API token secret for the user on the Proxmox Backup Server.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,

    /// Non-default port for Proxmox Backup Server.
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,

    /// Proxmox Backup Server ID.
    #[serde(rename = "remote")]
    pub remote: String,

    /// Proxmox Backup Server address.
    #[serde(rename = "server")]
    pub server: String,

    /// Username or API token ID on the Proxmox Backup Server
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,


}

impl ConfigPbsCreatePbsRequest {
    pub fn new(datastore: String, remote: String, server: String) -> ConfigPbsCreatePbsRequest {
        ConfigPbsCreatePbsRequest {
            
            datastore,
            
            disable: None,
            
            fingerprint: None,
            
            include_statistics: None,
            
            keep_daily: None,
            
            keep_hourly: None,
            
            keep_last: None,
            
            keep_monthly: None,
            
            keep_weekly: None,
            
            keep_yearly: None,
            
            namespace: None,
            
            notify: None,
            
            password: None,
            
            port: None,
            
            remote,
            
            server,
            
            username: None,
            
        }
    }
}


