/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigRuledbNotificationRequest {

    /// Attach original E-Mail
    #[serde(rename = "attach", skip_serializing_if = "Option::is_none")]
    pub attach: Option<models::PmgBoolean>,

    /// The Notification Body
    #[serde(rename = "body")]
    pub body: String,

    /// Informational comment.
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<String>,

    /// Action name.
    #[serde(rename = "name")]
    pub name: String,

    /// The Notification subject
    #[serde(rename = "subject")]
    pub subject: String,

    /// The Receiver E-Mail address
    #[serde(rename = "to")]
    pub to: String,


}

impl ConfigRuledbNotificationRequest {
    pub fn new(body: String, name: String, subject: String, to: String) -> ConfigRuledbNotificationRequest {
        ConfigRuledbNotificationRequest {
            
            attach: None,
            
            body,
            
            info: None,
            
            name,
            
            subject,
            
            to,
            
        }
    }
}


