/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigLdapUpdateConfigRequest {

    /// Account attribute name name.
    #[serde(rename = "accountattr", skip_serializing_if = "Option::is_none")]
    pub accountattr: Option<String>,

    /// Base domain name.
    #[serde(rename = "basedn", skip_serializing_if = "Option::is_none")]
    pub basedn: Option<String>,

    /// Bind domain name.
    #[serde(rename = "binddn", skip_serializing_if = "Option::is_none")]
    pub binddn: Option<String>,

    /// Bind password.
    #[serde(rename = "bindpw", skip_serializing_if = "Option::is_none")]
    pub bindpw: Option<String>,

    /// Path to CA file. Only useful with option 'verify'
    #[serde(rename = "cafile", skip_serializing_if = "Option::is_none")]
    pub cafile: Option<String>,

    /// Description.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// A list of settings you want to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<String>,

    /// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Flag to disable/deactivate the entry.
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<models::PmgBoolean>,

    /// LDAP filter.
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,

    /// Base domain name for groups.
    #[serde(rename = "groupbasedn", skip_serializing_if = "Option::is_none")]
    pub groupbasedn: Option<String>,

    /// List of objectclasses for groups.
    #[serde(rename = "groupclass", skip_serializing_if = "Option::is_none")]
    pub groupclass: Option<String>,

    /// List of mail attribute names.
    #[serde(rename = "mailattr", skip_serializing_if = "Option::is_none")]
    pub mailattr: Option<String>,

    /// LDAP protocol mode ('ldap', 'ldaps' or 'ldap+starttls').
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::PmgModeEnum>,

    /// Specify the port to connect to.
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,

    /// Server address.
    #[serde(rename = "server1", skip_serializing_if = "Option::is_none")]
    pub server1: Option<String>,

    /// Fallback server address. Userd when the first server is not available.
    #[serde(rename = "server2", skip_serializing_if = "Option::is_none")]
    pub server2: Option<String>,

    /// Verify server certificate. Only useful with ldaps or ldap+starttls.
    #[serde(rename = "verify", skip_serializing_if = "Option::is_none")]
    pub verify: Option<models::PmgBoolean>,


}

impl ConfigLdapUpdateConfigRequest {
    pub fn new() -> ConfigLdapUpdateConfigRequest {
        ConfigLdapUpdateConfigRequest {
            
            accountattr: None,
            
            basedn: None,
            
            binddn: None,
            
            bindpw: None,
            
            cafile: None,
            
            comment: None,
            
            delete: None,
            
            digest: None,
            
            disable: None,
            
            filter: None,
            
            groupbasedn: None,
            
            groupclass: None,
            
            mailattr: None,
            
            mode: None,
            
            port: None,
            
            server1: None,
            
            server2: None,
            
            verify: None,
            
        }
    }
}


