/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigRuledbDisclaimerRequest {

    /// If set to 1, adds a '--' separator between the disclaimer and the content. Set to 0 to prevent that.
    #[serde(rename = "add-separator", skip_serializing_if = "Option::is_none")]
    pub add_separator: Option<models::PmgBoolean>,

    /// The Disclaimer
    #[serde(rename = "disclaimer")]
    pub disclaimer: String,

    /// Informational comment.
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<String>,

    /// Action name.
    #[serde(rename = "name")]
    pub name: String,

    /// Put the disclaimer at the specified position.
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<models::PmgPositionEnum>,


}

impl ConfigRuledbDisclaimerRequest {
    pub fn new(disclaimer: String, name: String) -> ConfigRuledbDisclaimerRequest {
        ConfigRuledbDisclaimerRequest {
            
            add_separator: None,
            
            disclaimer,
            
            info: None,
            
            name,
            
            position: None,
            
        }
    }
}


