/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigMynetworksCreateMynetworksRequest {

    /// IPv4 or IPv6 network in CIDR notation.
    #[serde(rename = "cidr")]
    pub cidr: String,

    /// Comment.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,


}

impl ConfigMynetworksCreateMynetworksRequest {
    pub fn new(cidr: String) -> ConfigMynetworksCreateMynetworksRequest {
        ConfigMynetworksCreateMynetworksRequest {
            
            cidr,
            
            comment: None,
            
        }
    }
}


