/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigFetchmailWriteRequest {

    /// Flag to enable or disable polling.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<models::PmgBoolean>,

    /// Only check this site every <interval> poll cycles. A poll cycle is 5 minutes.
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<i32>,

    /// Keep retrieved messages on the remote mailserver.
    #[serde(rename = "keep", skip_serializing_if = "Option::is_none")]
    pub keep: Option<models::PmgBoolean>,

    /// The password used tfor server login.
    #[serde(rename = "pass", skip_serializing_if = "Option::is_none")]
    pub pass: Option<String>,

    /// Port number.
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,

    /// Specify  the  protocol to use when communicating with the remote mailserver
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<models::PmgProtocolEnum>,

    /// Server address (IP or DNS name).
    #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,

    /// Use SSL.
    #[serde(rename = "ssl", skip_serializing_if = "Option::is_none")]
    pub ssl: Option<models::PmgBoolean>,

    /// The target email address (where to deliver fetched mails).
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,

    /// The user identification to be used when logging in to the server
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,


}

impl ConfigFetchmailWriteRequest {
    pub fn new() -> ConfigFetchmailWriteRequest {
        ConfigFetchmailWriteRequest {
            
            enable: None,
            
            interval: None,
            
            keep: None,
            
            pass: None,
            
            port: None,
            
            protocol: None,
            
            server: None,
            
            ssl: None,
            
            target: None,
            
            user: None,
            
        }
    }
}


