/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigRuledbTimeframeRequest {

    /// End time in `H:i` format (00:00).
    #[serde(rename = "end")]
    pub end: String,

    /// Start time in `H:i` format (00:00).
    #[serde(rename = "start")]
    pub start: String,


}

impl ConfigRuledbTimeframeRequest {
    pub fn new(end: String, start: String) -> ConfigRuledbTimeframeRequest {
        ConfigRuledbTimeframeRequest {
            
            end,
            
            start,
            
        }
    }
}


