/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigTransportCreateTransportResponse {

    #[serde(rename = "data", deserialize_with = "Option::deserialize")]
    pub data: Option<serde_json::Value>,

    /// Optional total count, present for paginated list responses.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,

    /// Optional change summary returned by some PUT operations (one entry per modified field).
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<serde_json::Value>,


}

impl ConfigTransportCreateTransportResponse {
    pub fn new(data: Option<serde_json::Value>) -> ConfigTransportCreateTransportResponse {
        ConfigTransportCreateTransportResponse {
            
            data,
            
            total: None,
            
            changes: None,
            
        }
    }
}


