/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigRuledbCreateWhatGroupRequest {

    /// If set to 1, objects in this group are 'and' combined.
    #[serde(rename = "and", skip_serializing_if = "Option::is_none")]
    pub and: Option<models::PmgBoolean>,

    /// Informational comment.
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<String>,

    /// If set to 1, the resulting match is inverted.
    #[serde(rename = "invert", skip_serializing_if = "Option::is_none")]
    pub invert: Option<models::PmgBoolean>,

    /// Group name.
    #[serde(rename = "name")]
    pub name: String,


}

impl ConfigRuledbCreateWhatGroupRequest {
    pub fn new(name: String) -> ConfigRuledbCreateWhatGroupRequest {
        ConfigRuledbCreateWhatGroupRequest {
            
            and: None,
            
            info: None,
            
            invert: None,
            
            name,
            
        }
    }
}


