/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigRuledbConfigResponseData {

    #[serde(rename = "active")]
    pub active: models::PmgBoolean,

    #[serde(rename = "direction")]
    pub direction: i64,

    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "name")]
    pub name: String,

    #[serde(rename = "priority")]
    pub priority: i64,


}

impl ConfigRuledbConfigResponseData {
    pub fn new(active: models::PmgBoolean, direction: i64, id: i64, name: String, priority: i64) -> ConfigRuledbConfigResponseData {
        ConfigRuledbConfigResponseData {
            
            active,
            
            direction,
            
            id,
            
            name,
            
            priority,
            
        }
    }
}


