/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesBackupBackupRequest {

    /// Specify when to notify via e-mail
    #[serde(rename = "notify", skip_serializing_if = "Option::is_none")]
    pub notify: Option<models::PmgNotifyEnum>,

    /// Backup statistic databases.
    #[serde(rename = "statistic", skip_serializing_if = "Option::is_none")]
    pub statistic: Option<models::PmgBoolean>,


}

impl NodesBackupBackupRequest {
    pub fn new() -> NodesBackupBackupRequest {
        NodesBackupBackupRequest {
            
            notify: None,
            
            statistic: None,
            
        }
    }
}


