/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NodesStatusStatusResponseDataBootInfo : Meta-information about the boot mode.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStatusStatusResponseDataBootInfo {

    /// Through which firmware the system got booted.
    #[serde(rename = "mode")]
    pub mode: models::PmgNodesStatusModeEnum,

    /// System is booted in secure mode, only applicable for the \"efi\" mode.
    #[serde(rename = "secureboot", skip_serializing_if = "Option::is_none")]
    pub secureboot: Option<models::PmgBoolean>,


}

impl NodesStatusStatusResponseDataBootInfo {
    /// Meta-information about the boot mode.
    pub fn new(mode: models::PmgNodesStatusModeEnum) -> NodesStatusStatusResponseDataBootInfo {
        NodesStatusStatusResponseDataBootInfo {
            
            mode,
            
            secureboot: None,
            
        }
    }
}


