/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesBackupRestoreRequest {

    /// Restore system configuration.
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<models::PmgBoolean>,

    /// Restore the rule database. This is the default.
    #[serde(rename = "database", skip_serializing_if = "Option::is_none")]
    pub database: Option<models::PmgBoolean>,

    /// Restore statistic databases. Only considered when you restore the 'database'.
    #[serde(rename = "statistic", skip_serializing_if = "Option::is_none")]
    pub statistic: Option<models::PmgBoolean>,


}

impl NodesBackupRestoreRequest {
    pub fn new() -> NodesBackupRestoreRequest {
        NodesBackupRestoreRequest {
            
            config: None,
            
            database: None,
            
            statistic: None,
            
        }
    }
}


