/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStatusStatusResponseData {

    #[serde(rename = "boot-info")]
    pub boot_info: Box<models::NodesStatusStatusResponseDataBootInfo>,

    #[serde(rename = "current-kernel")]
    pub current_kernel: Box<models::NodesStatusStatusResponseDataCurrentKernel>,

    /// Database is synced with other nodes.
    #[serde(rename = "insync")]
    pub insync: models::PmgBoolean,

    /// Seconds since 1970-01-01 00:00:00 UTC.
    #[serde(rename = "time")]
    pub time: i64,

    /// The uptime of the system in seconds.
    #[serde(rename = "uptime")]
    pub uptime: i64,


}

impl NodesStatusStatusResponseData {
    pub fn new(boot_info: models::NodesStatusStatusResponseDataBootInfo, current_kernel: models::NodesStatusStatusResponseDataCurrentKernel, insync: models::PmgBoolean, time: i64, uptime: i64) -> NodesStatusStatusResponseData {
        NodesStatusStatusResponseData {
            
            boot_info: Box::new(boot_info),
            
            current_kernel: Box::new(current_kernel),
            
            insync,
            
            time,
            
            uptime,
            
        }
    }
}


