/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesPbsCreateTimerRequest {

    /// Randomized delay to add to the starttime (RandomizedDelaySec setting of the systemd.timer)
    #[serde(rename = "delay", skip_serializing_if = "Option::is_none")]
    pub delay: Option<String>,

    /// Schedule for the backup (OnCalendar setting of the systemd.timer)
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<String>,


}

impl NodesPbsCreateTimerRequest {
    pub fn new() -> NodesPbsCreateTimerRequest {
        NodesPbsCreateTimerRequest {
            
            delay: None,
            
            schedule: None,
            
        }
    }
}


