/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesCertificatesRenewAcmeCertRequest {

    /// Force renewal even if expiry is more than 30 days away.
    #[serde(rename = "force", skip_serializing_if = "Option::is_none")]
    pub force: Option<models::PmgBoolean>,


}

impl NodesCertificatesRenewAcmeCertRequest {
    pub fn new() -> NodesCertificatesRenewAcmeCertRequest {
        NodesCertificatesRenewAcmeCertRequest {
            
            force: None,
            
        }
    }
}


