/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptRepositoriesResponseDataErrorsInner {

    /// The error message
    #[serde(rename = "error")]
    pub error: String,

    /// Path to the problematic file.
    #[serde(rename = "path")]
    pub path: String,


}

impl NodesAptRepositoriesResponseDataErrorsInner {
    pub fn new(error: String, path: String) -> NodesAptRepositoriesResponseDataErrorsInner {
        NodesAptRepositoriesResponseDataErrorsInner {
            
            error,
            
            path,
            
        }
    }
}


