/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptRepositoriesResponseDataStandardReposInner {

    /// Description of the repository.
    #[serde(rename = "description")]
    pub description: String,

    /// Handle to identify the repository.
    #[serde(rename = "handle")]
    pub handle: String,

    /// Display name of the repository.
    #[serde(rename = "name")]
    pub name: String,

    /// Indicating enabled/disabled status, if the repository is configured.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::PmgBoolean>,


}

impl NodesAptRepositoriesResponseDataStandardReposInner {
    pub fn new(description: String, handle: String, name: String) -> NodesAptRepositoriesResponseDataStandardReposInner {
        NodesAptRepositoriesResponseDataStandardReposInner {
            
            description,
            
            handle,
            
            name,
            
            status: None,
            
        }
    }
}


