/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesGetNodesResponseDataInner {

    /// URL slug of the child resource (inferred from PVE HATEOAS link).
    #[serde(rename = "node")]
    pub node: String,

    /// Resource id of the form \"node/<name>\".
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// Resource type discriminator.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,

    /// Used disk space in bytes.
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<i64>,

    /// Total disk space in bytes.
    #[serde(rename = "maxdisk", skip_serializing_if = "Option::is_none")]
    pub maxdisk: Option<i64>,


}

impl NodesGetNodesResponseDataInner {
    pub fn new(node: String) -> NodesGetNodesResponseDataInner {
        NodesGetNodesResponseDataInner {
            
            node,
            
            id: None,
            
            r#type: None,
            
            disk: None,
            
            maxdisk: None,
            
        }
    }
}

/// Resource type discriminator.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "node")]
    Node,
}

impl Default for Type {
    fn default() -> Type {
        Self::Node
    }
}

