/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesClamavGetClamavResponseDataInner {

    /// URL slug of the child resource (inferred from PVE HATEOAS link).
    #[serde(rename = "subdir")]
    pub subdir: String,


}

impl NodesClamavGetClamavResponseDataInner {
    pub fn new(subdir: String) -> NodesClamavGetClamavResponseDataInner {
        NodesClamavGetClamavResponseDataInner {
            
            subdir,
            
        }
    }
}


