/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgNodesPostfixSortfieldEnum {
    #[serde(rename = "arrival_time")]
    ArrivalTime,
    #[serde(rename = "message_size")]
    MessageSize,
    #[serde(rename = "sender")]
    Sender,
    #[serde(rename = "receiver")]
    Receiver,
    #[serde(rename = "reason")]
    Reason,

}

impl std::fmt::Display for PmgNodesPostfixSortfieldEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ArrivalTime => write!(f, "arrival_time"),
            Self::MessageSize => write!(f, "message_size"),
            Self::Sender => write!(f, "sender"),
            Self::Receiver => write!(f, "receiver"),
            Self::Reason => write!(f, "reason"),
        }
    }
}

impl Default for PmgNodesPostfixSortfieldEnum {
    fn default() -> PmgNodesPostfixSortfieldEnum {
        Self::ArrivalTime
    }
}

