/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PmgAcmedomainConfig {

    /// Alias for the Domain to verify ACME Challenge over DNS
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,

    /// domain for this node's ACME certificate
    #[serde(rename = "domain")]
    pub domain: String,

    /// The ACME plugin ID
    #[serde(rename = "plugin", skip_serializing_if = "Option::is_none")]
    pub plugin: Option<String>,

    /// Whether this domain is used for the API, SMTP or both
    #[serde(rename = "usage")]
    pub usage: String,


}

impl PmgAcmedomainConfig {
    pub fn new(domain: String, usage: String) -> PmgAcmedomainConfig {
        PmgAcmedomainConfig {
            
            alias: None,
            
            domain,
            
            plugin: None,
            
            usage,
            
        }
    }
}


