/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgConfigAcmeTypeEnum {
    #[serde(rename = "dns")]
    Dns,
    #[serde(rename = "standalone")]
    Standalone,

}

impl std::fmt::Display for PmgConfigAcmeTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Dns => write!(f, "dns"),
            Self::Standalone => write!(f, "standalone"),
        }
    }
}

impl Default for PmgConfigAcmeTypeEnum {
    fn default() -> PmgConfigAcmeTypeEnum {
        Self::Dns
    }
}

