/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgConfigAdminDkimUseDomainEnum {
    #[serde(rename = "header")]
    Header,
    #[serde(rename = "envelope")]
    Envelope,

}

impl std::fmt::Display for PmgConfigAdminDkimUseDomainEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Header => write!(f, "header"),
            Self::Envelope => write!(f, "envelope"),
        }
    }
}

impl Default for PmgConfigAdminDkimUseDomainEnum {
    fn default() -> PmgConfigAdminDkimUseDomainEnum {
        Self::Header
    }
}

