/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgAccessAuthRealmTypeEnum {
    #[serde(rename = "oidc")]
    Oidc,
    #[serde(rename = "pam")]
    Pam,
    #[serde(rename = "pmg")]
    Pmg,

}

impl std::fmt::Display for PmgAccessAuthRealmTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Oidc => write!(f, "oidc"),
            Self::Pam => write!(f, "pam"),
            Self::Pmg => write!(f, "pmg"),
        }
    }
}

impl Default for PmgAccessAuthRealmTypeEnum {
    fn default() -> PmgAccessAuthRealmTypeEnum {
        Self::Oidc
    }
}

