/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PmgAutocreateRoleAssignmentField {
    PmgAutocreateRoleAssignmentConfig(Box<models::PmgAutocreateRoleAssignmentConfig>),
    String(String),
}

impl Default for PmgAutocreateRoleAssignmentField {
    fn default() -> Self {
        Self::PmgAutocreateRoleAssignmentConfig(Default::default())
    }
}

