/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgQuarantineContentActionEnum {
    #[serde(rename = "welcomelist")]
    Welcomelist,
    #[serde(rename = "blocklist")]
    Blocklist,
    #[serde(rename = "whitelist")]
    Whitelist,
    #[serde(rename = "blacklist")]
    Blacklist,
    #[serde(rename = "deliver")]
    Deliver,
    #[serde(rename = "delete")]
    Delete,

}

impl std::fmt::Display for PmgQuarantineContentActionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Welcomelist => write!(f, "welcomelist"),
            Self::Blocklist => write!(f, "blocklist"),
            Self::Whitelist => write!(f, "whitelist"),
            Self::Blacklist => write!(f, "blacklist"),
            Self::Deliver => write!(f, "deliver"),
            Self::Delete => write!(f, "delete"),
        }
    }
}

impl Default for PmgQuarantineContentActionEnum {
    fn default() -> PmgQuarantineContentActionEnum {
        Self::Welcomelist
    }
}

