/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgConfigMailProtocolEnum {
    #[serde(rename = "smtp")]
    Smtp,
    #[serde(rename = "lmtp")]
    Lmtp,

}

impl std::fmt::Display for PmgConfigMailProtocolEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Smtp => write!(f, "smtp"),
            Self::Lmtp => write!(f, "lmtp"),
        }
    }
}

impl Default for PmgConfigMailProtocolEnum {
    fn default() -> PmgConfigMailProtocolEnum {
        Self::Smtp
    }
}

