/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgConfigSpamquarAuthmodeEnum {
    #[serde(rename = "ticket")]
    Ticket,
    #[serde(rename = "ldap")]
    Ldap,
    #[serde(rename = "ldapticket")]
    Ldapticket,

}

impl std::fmt::Display for PmgConfigSpamquarAuthmodeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ticket => write!(f, "ticket"),
            Self::Ldap => write!(f, "ldap"),
            Self::Ldapticket => write!(f, "ldapticket"),
        }
    }
}

impl Default for PmgConfigSpamquarAuthmodeEnum {
    fn default() -> PmgConfigSpamquarAuthmodeEnum {
        Self::Ticket
    }
}

