/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgNodesCfEnum {
    #[serde(rename = "AVERAGE")]
    Average,
    #[serde(rename = "MAX")]
    Max,

}

impl std::fmt::Display for PmgNodesCfEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Average => write!(f, "AVERAGE"),
            Self::Max => write!(f, "MAX"),
        }
    }
}

impl Default for PmgNodesCfEnum {
    fn default() -> PmgNodesCfEnum {
        Self::Average
    }
}

