/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgNotifyEnum {
    #[serde(rename = "always")]
    Always,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "never")]
    Never,

}

impl std::fmt::Display for PmgNotifyEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Always => write!(f, "always"),
            Self::Error => write!(f, "error"),
            Self::Never => write!(f, "never"),
        }
    }
}

impl Default for PmgNotifyEnum {
    fn default() -> PmgNotifyEnum {
        Self::Always
    }
}

