/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgFileTypeEnum {
    #[serde(rename = "list")]
    List,
    #[serde(rename = "sources")]
    Sources,

}

impl std::fmt::Display for PmgFileTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::List => write!(f, "list"),
            Self::Sources => write!(f, "sources"),
        }
    }
}

impl Default for PmgFileTypeEnum {
    fn default() -> PmgFileTypeEnum {
        Self::List
    }
}

