/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PmgNodesPostfixActionEnum {
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "deliver")]
    Deliver,

}

impl std::fmt::Display for PmgNodesPostfixActionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Delete => write!(f, "delete"),
            Self::Deliver => write!(f, "deliver"),
        }
    }
}

impl Default for PmgNodesPostfixActionEnum {
    fn default() -> PmgNodesPostfixActionEnum {
        Self::Delete
    }
}

