/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuarantineListattachmentsResponseDataInner {

    /// Raw email header data.
    #[serde(rename = "content-type")]
    pub content_type: String,

    /// Attachment ID
    #[serde(rename = "id")]
    pub id: i64,

    /// Raw email header data.
    #[serde(rename = "name")]
    pub name: String,

    /// Size of raw attachment in bytes.
    #[serde(rename = "size")]
    pub size: i64,


}

impl QuarantineListattachmentsResponseDataInner {
    pub fn new(content_type: String, id: i64, name: String, size: i64) -> QuarantineListattachmentsResponseDataInner {
        QuarantineListattachmentsResponseDataInner {
            
            content_type,
            
            id,
            
            name,
            
            size,
            
        }
    }
}


