/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuarantineBlacklistBlacklistAddRequest {

    /// The address you want to add.
    #[serde(rename = "address")]
    pub address: String,

    /// List entries for the user with this primary email address. Quarantine users cannot specify this parameter, but it is required for all other roles.
    #[serde(rename = "pmail", skip_serializing_if = "Option::is_none")]
    pub pmail: Option<String>,


}

impl QuarantineBlacklistBlacklistAddRequest {
    pub fn new(address: String) -> QuarantineBlacklistBlacklistAddRequest {
        QuarantineBlacklistBlacklistAddRequest {
            
            address,
            
            pmail: None,
            
        }
    }
}


