/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatisticsMailcountResponseDataInner {

    /// Incoming bounce mail count (sender = <>).
    #[serde(rename = "bounces_in")]
    pub bounces_in: f64,

    /// Outgoing bounce mail count (sender = <>).
    #[serde(rename = "bounces_out")]
    pub bounces_out: f64,

    /// Overall mail count (in and out).
    #[serde(rename = "count")]
    pub count: f64,

    /// Incoming mail count.
    #[serde(rename = "count_in")]
    pub count_in: f64,

    /// Outgoing mail count.
    #[serde(rename = "count_out")]
    pub count_out: f64,

    /// Time index.
    #[serde(rename = "index")]
    pub index: i64,

    /// PREGREET reject count.
    #[serde(rename = "pregreet_rejects")]
    pub pregreet_rejects: i64,

    /// Number of RBL rejects.
    #[serde(rename = "rbl_rejects")]
    pub rbl_rejects: i64,

    /// Incoming spam mails (spamcount_in + glcount + spfcount + rbl_rejects + pregreet_rejects).
    #[serde(rename = "spamcount_in")]
    pub spamcount_in: f64,

    /// Outgoing spam mails.
    #[serde(rename = "spamcount_out")]
    pub spamcount_out: f64,

    /// Time (Unix epoch).
    #[serde(rename = "time")]
    pub time: i64,

    /// Number of incoming virus mails.
    #[serde(rename = "viruscount_in")]
    pub viruscount_in: f64,

    /// Number of outgoing virus mails.
    #[serde(rename = "viruscount_out")]
    pub viruscount_out: f64,


}

impl StatisticsMailcountResponseDataInner {
    pub fn new(bounces_in: f64, bounces_out: f64, count: f64, count_in: f64, count_out: f64, index: i64, pregreet_rejects: i64, rbl_rejects: i64, spamcount_in: f64, spamcount_out: f64, time: i64, viruscount_in: f64, viruscount_out: f64) -> StatisticsMailcountResponseDataInner {
        StatisticsMailcountResponseDataInner {
            
            bounces_in,
            
            bounces_out,
            
            count,
            
            count_in,
            
            count_out,
            
            index,
            
            pregreet_rejects,
            
            rbl_rejects,
            
            spamcount_in,
            
            spamcount_out,
            
            time,
            
            viruscount_in,
            
            viruscount_out,
            
        }
    }
}


