/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatisticsMailResponseData {

    /// Average mail processing time in seconds.
    #[serde(rename = "avptime")]
    pub avptime: f64,

    /// Incoming bounce mail count (sender = <>).
    #[serde(rename = "bounces_in")]
    pub bounces_in: f64,

    /// Outgoing bounce mail count (sender = <>).
    #[serde(rename = "bounces_out")]
    pub bounces_out: f64,

    /// Incoming mail traffic (bytes).
    #[serde(rename = "bytes_in")]
    pub bytes_in: f64,

    /// Outgoing mail traffic (bytes).
    #[serde(rename = "bytes_out")]
    pub bytes_out: f64,

    /// Overall mail count (in and out).
    #[serde(rename = "count")]
    pub count: f64,

    /// Incoming mail count.
    #[serde(rename = "count_in")]
    pub count_in: f64,

    /// Outgoing mail count.
    #[serde(rename = "count_out")]
    pub count_out: f64,

    /// Number of greylisted mails.
    #[serde(rename = "glcount")]
    pub glcount: f64,

    /// Incoming junk mail count (viruscount_in + spamcount_in + glcount + spfcount + rbl_rejects + pregreet_rejects).
    #[serde(rename = "junk_in")]
    pub junk_in: f64,

    /// Outgoing junk mail count (viruscount_out + spamcount_out).
    #[serde(rename = "junk_out")]
    pub junk_out: f64,

    /// PREGREET reject count.
    #[serde(rename = "pregreet_rejects")]
    pub pregreet_rejects: i64,

    /// Number of RBL rejects.
    #[serde(rename = "rbl_rejects")]
    pub rbl_rejects: i64,

    /// Incoming spam mails.
    #[serde(rename = "spamcount_in")]
    pub spamcount_in: f64,

    /// Outgoing spam mails.
    #[serde(rename = "spamcount_out")]
    pub spamcount_out: f64,

    /// Mails rejected by SPF.
    #[serde(rename = "spfcount")]
    pub spfcount: f64,

    /// Number of incoming virus mails.
    #[serde(rename = "viruscount_in")]
    pub viruscount_in: f64,

    /// Number of outgoing virus mails.
    #[serde(rename = "viruscount_out")]
    pub viruscount_out: f64,


}

impl StatisticsMailResponseData {
    pub fn new(avptime: f64, bounces_in: f64, bounces_out: f64, bytes_in: f64, bytes_out: f64, count: f64, count_in: f64, count_out: f64, glcount: f64, junk_in: f64, junk_out: f64, pregreet_rejects: i64, rbl_rejects: i64, spamcount_in: f64, spamcount_out: f64, spfcount: f64, viruscount_in: f64, viruscount_out: f64) -> StatisticsMailResponseData {
        StatisticsMailResponseData {
            
            avptime,
            
            bounces_in,
            
            bounces_out,
            
            bytes_in,
            
            bytes_out,
            
            count,
            
            count_in,
            
            count_out,
            
            glcount,
            
            junk_in,
            
            junk_out,
            
            pregreet_rejects,
            
            rbl_rejects,
            
            spamcount_in,
            
            spamcount_out,
            
            spfcount,
            
            viruscount_in,
            
            viruscount_out,
            
        }
    }
}


