/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatisticsRecentResponseDataInner {

    /// Number of incoming bytes mails.
    #[serde(rename = "bytes_in")]
    pub bytes_in: f64,

    /// Number of outgoing bytes mails.
    #[serde(rename = "bytes_out")]
    pub bytes_out: f64,

    /// Overall mail count (in and out).
    #[serde(rename = "count")]
    pub count: f64,

    /// Incoming mail count.
    #[serde(rename = "count_in")]
    pub count_in: f64,

    /// Outgoing mail count.
    #[serde(rename = "count_out")]
    pub count_out: f64,

    /// Time index.
    #[serde(rename = "index")]
    pub index: i64,

    /// Overall spam mail count (in and out).
    #[serde(rename = "spam")]
    pub spam: f64,

    /// Incoming spam mails (spamcount_in + glcount + spfcount).
    #[serde(rename = "spam_in")]
    pub spam_in: f64,

    /// Outgoing spam mails.
    #[serde(rename = "spam_out")]
    pub spam_out: f64,

    /// Time (Unix epoch).
    #[serde(rename = "time")]
    pub time: i64,

    /// Timespan in seconds for one data point
    #[serde(rename = "timespan")]
    pub timespan: f64,

    /// Number of incoming virus mails.
    #[serde(rename = "virus_in")]
    pub virus_in: f64,

    /// Number of outgoing virus mails.
    #[serde(rename = "virus_out")]
    pub virus_out: f64,


}

impl StatisticsRecentResponseDataInner {
    pub fn new(bytes_in: f64, bytes_out: f64, count: f64, count_in: f64, count_out: f64, index: i64, spam: f64, spam_in: f64, spam_out: f64, time: i64, timespan: f64, virus_in: f64, virus_out: f64) -> StatisticsRecentResponseDataInner {
        StatisticsRecentResponseDataInner {
            
            bytes_in,
            
            bytes_out,
            
            count,
            
            count_in,
            
            count_out,
            
            index,
            
            spam,
            
            spam_in,
            
            spam_out,
            
            time,
            
            timespan,
            
            virus_in,
            
            virus_out,
            
        }
    }
}


