/*
 * Proxmox Mail Gateway API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pmg.proxmox.com/pmg-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatisticsSpamscoresResponseDataInner {

    /// Detection count.
    #[serde(rename = "count")]
    pub count: i64,

    /// Spam level.
    #[serde(rename = "level")]
    pub level: String,

    /// Portion of overall mail count.
    #[serde(rename = "ratio")]
    pub ratio: f64,


}

impl StatisticsSpamscoresResponseDataInner {
    pub fn new(count: i64, level: String, ratio: f64) -> StatisticsSpamscoresResponseDataInner {
        StatisticsSpamscoresResponseDataInner {
            
            count,
            
            level,
            
            ratio,
            
        }
    }
}


